#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Feb 17 12:27:59 MST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
