#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Fri Feb 13 23:46:00 MST 2026
alwaysLogTamperWarnings=false
